export const APP_ROLES = {
  PUBLIC_VISITOR: 'PUBLIC_VISITOR',
  RESEARCHER: 'RESEARCHER',
  STUDENT_RESEARCH_ASSISTANT: 'STUDENT_RESEARCH_ASSISTANT',
  DEPARTMENT_COORDINATOR: 'DEPARTMENT_COORDINATOR',
  ORIC_STAFF: 'ORIC_STAFF',
  PORTAL_ADMIN: 'PORTAL_ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
} as const;

export type AppRoleName = (typeof APP_ROLES)[keyof typeof APP_ROLES];

