import {
  Department,
  JointArticleMapPoint,
  NewsItem,
  Project,
  Publication,
  ResearchArea,
  ResearchGroup,
  Researcher,
  Thesis,
} from '../types/portal';

export const researchAreas: ResearchArea[] = [
  {
    id: 'ra-ai',
    name: 'Artificial Intelligence',
    slug: 'artificial-intelligence',
    description: 'Machine learning, language technologies, embedded intelligence, and applied analytics.',
  },
  {
    id: 'ra-cyber',
    name: 'Cyber Security',
    slug: 'cyber-security',
    description: 'Secure systems, digital forensics, cyber resilience, and privacy engineering.',
  },
  {
    id: 'ra-energy',
    name: 'Sustainable Energy Systems',
    slug: 'sustainable-energy-systems',
    description: 'Distributed energy, power optimization, smart grids, and energy efficiency.',
  },
  {
    id: 'ra-health',
    name: 'Digital Health',
    slug: 'digital-health',
    description: 'Clinical informatics, assistive systems, decision support, and health data platforms.',
  },
];

export const departments: Department[] = [
  {
    id: 'dep-cs',
    name: 'Department of Computer Science',
    slug: 'computer-science',
    description: 'Research in intelligent systems, software engineering, human-centered computing, and secure platforms.',
    faculty: 'Faculty of Science and Technology',
    stats: { researchers: 22, publications: 118, projects: 14, theses: 37 },
  },
  {
    id: 'dep-ee',
    name: 'Department of Electrical Engineering',
    slug: 'electrical-engineering',
    description: 'Research spanning embedded systems, control, communication engineering, and energy systems.',
    faculty: 'Faculty of Engineering',
    stats: { researchers: 16, publications: 94, projects: 11, theses: 25 },
  },
  {
    id: 'dep-bms',
    name: 'Department of Management Sciences',
    slug: 'management-sciences',
    description: 'Research in innovation, digital transformation, entrepreneurship, and public sector performance.',
    faculty: 'Faculty of Social Sciences',
    stats: { researchers: 12, publications: 63, projects: 7, theses: 19 },
  },
];

export const researchers: Researcher[] = [
  {
    id: 'res-sara',
    slug: 'dr-sara-khalid',
    firstName: 'Sara',
    lastName: 'Khalid',
    designation: 'Associate Professor, AI and Data Systems',
    departmentSlug: 'computer-science',
    faculty: 'Faculty of Science and Technology',
    expertiseSummary: 'Works on multimodal learning, academic knowledge discovery, and explainable AI for public-sector decision support.',
    biography:
      'Dr. Sara Khalid leads interdisciplinary research at LGU connecting machine learning, research intelligence, and civic data systems. Her recent work focuses on explainable models for institutional planning and student success.',
    researchAreas: ['Artificial Intelligence', 'Digital Health'],
    email: 'sara.khalid@lgu.edu.pk',
    featured: true,
    stats: { publications: 29, projects: 6, citationsLabel: '1,240 citations' },
  },
  {
    id: 'res-usman',
    slug: 'dr-usman-farooq',
    firstName: 'Usman',
    lastName: 'Farooq',
    designation: 'Professor, Secure Systems Engineering',
    departmentSlug: 'computer-science',
    faculty: 'Faculty of Science and Technology',
    expertiseSummary: 'Builds resilient networked systems, cyber training environments, and security analytics pipelines.',
    biography:
      'Dr. Usman Farooq coordinates LGU security research initiatives with a focus on incident response automation, secure architectures, and digital forensics readiness.',
    researchAreas: ['Cyber Security', 'Artificial Intelligence'],
    email: 'usman.farooq@lgu.edu.pk',
    featured: true,
    stats: { publications: 41, projects: 8, citationsLabel: '1,980 citations' },
  },
  {
    id: 'res-aiman',
    slug: 'dr-aiman-shah',
    firstName: 'Aiman',
    lastName: 'Shah',
    designation: 'Assistant Professor, Smart Energy Systems',
    departmentSlug: 'electrical-engineering',
    faculty: 'Faculty of Engineering',
    expertiseSummary: 'Studies smart-grid forecasting, demand response optimization, and intelligent energy monitoring.',
    biography:
      'Dr. Aiman Shah develops forecasting and optimization systems for campus-scale power infrastructure and urban energy planning.',
    researchAreas: ['Sustainable Energy Systems'],
    email: 'aiman.shah@lgu.edu.pk',
    featured: true,
    stats: { publications: 18, projects: 5, citationsLabel: '860 citations' },
  },
  {
    id: 'res-hadia',
    slug: 'dr-hadia-waseem',
    firstName: 'Hadia',
    lastName: 'Waseem',
    designation: 'Lecturer, Innovation and Digital Strategy',
    departmentSlug: 'management-sciences',
    faculty: 'Faculty of Social Sciences',
    expertiseSummary: 'Explores digital transformation capability, innovation governance, and institutional research culture.',
    biography:
      'Dr. Hadia Waseem studies how universities and public organizations build sustainable digital innovation capability with measurable outcomes.',
    researchAreas: ['Artificial Intelligence'],
    email: 'hadia.waseem@lgu.edu.pk',
    featured: false,
    stats: { publications: 11, projects: 3, citationsLabel: '310 citations' },
  },
];

export const groups: ResearchGroup[] = [
  {
    id: 'grp-knowledge-systems',
    name: 'Knowledge Systems and Discovery Lab',
    slug: 'knowledge-systems-and-discovery-lab',
    description: 'A cross-disciplinary lab for semantic search, research intelligence, information extraction, and institutional analytics.',
    departmentSlug: 'computer-science',
    lead: 'dr-sara-khalid',
    focusAreas: ['Artificial Intelligence', 'Digital Health'],
    membersCount: 14,
    projectsCount: 5,
    publicationsCount: 24,
  },
  {
    id: 'grp-cyber-range',
    name: 'Cyber Resilience and Forensics Group',
    slug: 'cyber-resilience-and-forensics-group',
    description: 'Focused on secure architectures, cyber defense simulation, forensic workflows, and operational resilience.',
    departmentSlug: 'computer-science',
    lead: 'dr-usman-farooq',
    focusAreas: ['Cyber Security'],
    membersCount: 11,
    projectsCount: 4,
    publicationsCount: 21,
  },
  {
    id: 'grp-smart-grid',
    name: 'Smart Grid Optimization Unit',
    slug: 'smart-grid-optimization-unit',
    description: 'Researches smart metering, predictive control, renewable integration, and energy-aware campus infrastructure.',
    departmentSlug: 'electrical-engineering',
    lead: 'dr-aiman-shah',
    focusAreas: ['Sustainable Energy Systems'],
    membersCount: 9,
    projectsCount: 3,
    publicationsCount: 12,
  },
];

export const publications: Publication[] = [
  {
    id: 'pub-research-search',
    slug: 'semantic-ranking-for-university-research-discovery',
    title: 'Semantic Ranking for University Research Discovery Using Faculty, Project, and Output Signals',
    abstract: 'Introduces a hybrid ranking pipeline for academic portals that blends researcher authority, semantic relevance, and institutional context.',
    publicationType: 'Journal Article',
    journalOrConference: 'Journal of Information Discovery Systems',
    doi: '10.5555/lgu.2026.001',
    publicationDate: '2026-02-10',
    departmentSlug: 'computer-science',
    authorSlugs: ['dr-sara-khalid', 'dr-usman-farooq'],
    researchAreas: ['Artificial Intelligence'],
    openAccess: true,
  },
  {
    id: 'pub-cyber-triage',
    slug: 'adaptive-triage-in-campus-cyber-incidents',
    title: 'Adaptive Triage in Campus Cyber Incidents Through Context-Aware Alert Prioritization',
    abstract: 'Presents a contextual triage model that reduces investigation fatigue in university security operations.',
    publicationType: 'Conference Paper',
    journalOrConference: 'International Conference on Applied Cyber Defense',
    doi: '10.5555/lgu.2025.014',
    publicationDate: '2025-11-18',
    departmentSlug: 'computer-science',
    authorSlugs: ['dr-usman-farooq'],
    researchAreas: ['Cyber Security'],
    openAccess: false,
  },
  {
    id: 'pub-grid-forecasting',
    slug: 'forecasting-campus-load-through-lightweight-smart-grid-models',
    title: 'Forecasting Campus Load Through Lightweight Smart-Grid Models for Resource-Constrained Deployments',
    abstract: 'Explores forecasting methods for campuses with limited sensing infrastructure and varying seasonal load patterns.',
    publicationType: 'Journal Article',
    journalOrConference: 'Energy Informatics Review',
    doi: '10.5555/lgu.2025.031',
    publicationDate: '2025-08-02',
    departmentSlug: 'electrical-engineering',
    authorSlugs: ['dr-aiman-shah'],
    researchAreas: ['Sustainable Energy Systems'],
    openAccess: true,
  },
];

export const projects: Project[] = [
  {
    id: 'proj-oric-insights',
    slug: 'lgu-research-intelligence-and-discovery-platform',
    title: 'LGU Research Intelligence and Discovery Platform',
    abstract: 'A university-wide initiative to unify researcher profiles, outputs, search, and analytics into one discoverable ecosystem.',
    departmentSlug: 'computer-science',
    status: 'Active',
    fundingAgency: 'LGU ORIC',
    budgetLabel: 'PKR 4.8M',
    principalInvestigatorSlug: 'dr-sara-khalid',
    members: ['dr-usman-farooq', 'dr-hadia-waseem'],
    researchAreas: ['Artificial Intelligence'],
    publicationSlugs: ['semantic-ranking-for-university-research-discovery'],
    startDate: '2025-09-01',
    endDate: '2027-06-30',
  },
  {
    id: 'proj-cyber-range',
    slug: 'campus-cyber-range-and-incident-readiness-program',
    title: 'Campus Cyber Range and Incident Readiness Program',
    abstract: 'Builds a realistic learning and research environment for cyber drills, detection engineering, and response playbooks.',
    departmentSlug: 'computer-science',
    status: 'Active',
    fundingAgency: 'National Cyber Security Initiative',
    budgetLabel: 'PKR 7.2M',
    principalInvestigatorSlug: 'dr-usman-farooq',
    members: ['dr-sara-khalid'],
    researchAreas: ['Cyber Security'],
    publicationSlugs: ['adaptive-triage-in-campus-cyber-incidents'],
    startDate: '2024-05-15',
    endDate: '2026-12-20',
  },
  {
    id: 'proj-smart-campus',
    slug: 'smart-campus-energy-forecasting-and-optimization',
    title: 'Smart Campus Energy Forecasting and Optimization',
    abstract: 'Combines energy forecasting, occupancy patterns, and control recommendations to reduce campus operational waste.',
    departmentSlug: 'electrical-engineering',
    status: 'Completed',
    fundingAgency: 'Higher Education Innovation Fund',
    budgetLabel: 'PKR 3.6M',
    principalInvestigatorSlug: 'dr-aiman-shah',
    members: [],
    researchAreas: ['Sustainable Energy Systems'],
    publicationSlugs: ['forecasting-campus-load-through-lightweight-smart-grid-models'],
    startDate: '2023-01-10',
    endDate: '2025-01-15',
  },
];

export const theses: Thesis[] = [
  {
    id: 'thesis-semantic-search',
    slug: 'semantic-search-patterns-for-academic-research-portals',
    title: 'Semantic Search Patterns for Academic Research Portals',
    abstract: 'Examines retrieval and ranking strategies for research discovery systems in university contexts.',
    degreeLevel: 'MS',
    studentName: 'Mahnoor Tariq',
    supervisorSlug: 'dr-sara-khalid',
    departmentSlug: 'computer-science',
    submissionDate: '2025-12-12',
    researchArea: 'Artificial Intelligence',
  },
  {
    id: 'thesis-threat-intel',
    slug: 'threat-intelligence-prioritization-for-university-networks',
    title: 'Threat Intelligence Prioritization for University Networks',
    abstract: 'Designs a scoring approach to align campus detection workflows with contextual threat intelligence.',
    degreeLevel: 'MS',
    studentName: 'Hassan Javed',
    supervisorSlug: 'dr-usman-farooq',
    departmentSlug: 'computer-science',
    submissionDate: '2025-09-08',
    researchArea: 'Cyber Security',
  },
  {
    id: 'thesis-load-optimization',
    slug: 'load-optimization-for-smart-campus-distribution-systems',
    title: 'Load Optimization for Smart Campus Distribution Systems',
    abstract: 'Evaluates demand-side optimization strategies for campus micro-distribution networks.',
    degreeLevel: 'PhD',
    studentName: 'Mariam Saleem',
    supervisorSlug: 'dr-aiman-shah',
    departmentSlug: 'electrical-engineering',
    submissionDate: '2024-11-21',
    researchArea: 'Sustainable Energy Systems',
  },
];

export const newsItems: NewsItem[] = [
  {
    id: 'news-oric-showcase',
    slug: 'lgu-research-showcase-highlights-interdisciplinary-projects',
    title: 'LGU Research Showcase Highlights Interdisciplinary Projects Across Faculties',
    summary: 'Faculty teams presented applied research in AI, cyber resilience, digital policy, and energy optimization.',
    category: 'Event',
    publishedAt: '2026-03-15',
  },
  {
    id: 'news-grant-award',
    slug: 'lgu-secures-support-for-campus-cyber-range-expansion',
    title: 'LGU Secures Support for Campus Cyber Range Expansion',
    summary: 'The new phase extends infrastructure for incident simulation, forensic training, and collaborative defense exercises.',
    category: 'News',
    publishedAt: '2026-02-05',
    departmentSlug: 'computer-science',
  },
  {
    id: 'news-energy-briefing',
    slug: 'smart-energy-team-releases-campus-efficiency-briefing',
    title: 'Smart Energy Team Releases Campus Efficiency Briefing',
    summary: 'The briefing outlines measurable reductions in power waste through forecasting and scheduling improvements.',
    category: 'Activity',
    publishedAt: '2025-12-01',
    departmentSlug: 'electrical-engineering',
  },
];

export const joinResearchOpportunities = [
  {
    id: 'opp-ra-1',
    title: 'MS Research Assistant in Academic Search',
    summary:
      'Assist with ranking experiments, metadata cleanup, and UI testing for the LGU research discovery platform.',
    departmentSlug: 'computer-science',
    href: '/projects/lgu-research-intelligence-and-discovery-platform',
    label: 'Open assistantship',
  },
  {
    id: 'opp-ra-2',
    title: 'Cyber Range Student Volunteer Cohort',
    summary:
      'Support incident simulation exercises, capture lab observations, and help prepare demonstration scenarios.',
    departmentSlug: 'computer-science',
    href: '/groups/cyber-resilience-and-forensics-group',
    label: 'Volunteer call',
  },
  {
    id: 'opp-ra-3',
    title: 'Final-Year Thesis Track in Smart Energy Analytics',
    summary:
      'Join supervised thesis work on campus load forecasting, scheduling, and energy efficiency dashboards.',
    departmentSlug: 'electrical-engineering',
    href: '/theses',
    label: 'Thesis pathway',
  },
];

export const jointArticleMapPoints: JointArticleMapPoint[] = [
  {
    id: 'map-uk',
    country: 'United Kingdom',
    x: 374,
    y: 118,
    articleTitle: 'Knowledge Graph Signals for Institutional Research Discovery',
    href: '/publications/semantic-ranking-for-university-research-discovery',
    articleType: 'Joint Journal Article',
    partnerInstitution: 'University of Manchester',
    year: '2026',
    summary:
      'A co-authored publication on ranking institutional research records using graph-aware semantic signals.',
  },
  {
    id: 'map-germany',
    country: 'Germany',
    x: 405,
    y: 122,
    articleTitle: 'Secure Alert Prioritization in University SOC Environments',
    href: '/publications/adaptive-triage-in-campus-cyber-incidents',
    articleType: 'Conference Paper',
    partnerInstitution: 'Technical University of Munich',
    year: '2025',
    summary:
      'Joint work on contextual security triage for academic networks and campus-scale security operations.',
  },
  {
    id: 'map-saudi',
    country: 'Saudi Arabia',
    x: 485,
    y: 177,
    articleTitle: 'Applied Collaboration Models for Cross-Border Digital Health Research',
    href: '/researchers/dr-sara-khalid',
    articleType: 'Collaborative Article',
    partnerInstitution: 'King Saud University',
    year: '2025',
    summary:
      'A collaboration focused on academic-health data interoperability and applied research translation.',
  },
  {
    id: 'map-china',
    country: 'China',
    x: 655,
    y: 152,
    articleTitle: 'Lightweight Smart-Grid Forecasting for Resource-Constrained Campuses',
    href: '/publications/forecasting-campus-load-through-lightweight-smart-grid-models',
    articleType: 'Joint Journal Article',
    partnerInstitution: 'Shanghai Jiao Tong University',
    year: '2025',
    summary:
      'Joint publication on forecasting campus energy demand with low-overhead modeling approaches.',
  },
  {
    id: 'map-malaysia',
    country: 'Malaysia',
    x: 629,
    y: 226,
    articleTitle: 'Academic Portal Search Experience Design for Emerging Research Ecosystems',
    href: '/projects/lgu-research-intelligence-and-discovery-platform',
    articleType: 'Proceeding',
    partnerInstitution: 'Universiti Malaya',
    year: '2026',
    summary:
      'Cross-country work on discoverability patterns for university research portals and metadata systems.',
  },
];
